# Generated by Django 5.0.6 on 2024-06-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeed',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/'),
        ),
        migrations.CreateModel(
            name='DescribedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(max_length=100)),
                ('image_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='described_image', to='object_detection.imagefeed')),
            ],
        ),
    ]
